agent_name: "minimal_memory_agent_qwen_converted"
# model_name: "./converted_ckpt/qwen2.5-step60"
model_name: "Qwen/Qwen2.5-7B-Instruct"
enable_thinking: false
vllm: true
thinking_budget: 1024
max_new_tokens: 2048

infer_with_full_memory: true
external_model_url: http://10.202.0.8:5000
api_key: EMPTY
